
CREATE TABLE `TEST_DEMO` (
`ID` VARCHAR(64) NOT NULL COMMENT '主键',
    PRIMARY KEY (`ID`),
    `bpm_status` VARCHAR(64) DEFAULT NULL COMMENT '流程状态',
    `TEST_ORG` VARCHAR(64) DEFAULT NULL COMMENT '机构Id',
    `TEST_NAME` VARCHAR(64) DEFAULT NULL COMMENT '名称',
        `BPM_STATE` int(1) DEFAULT NULL,
        `TENANT_ID` varchar(64) DEFAULT NULL,
        `DR` int(11) DEFAULT NULL COMMENT '是否删除',
        `TS` varchar(64) DEFAULT NULL COMMENT '时间戳',
        `LAST_MODIFIED` varchar(64) DEFAULT NULL COMMENT '修改时间',
        `LAST_MODIFY_USER` varchar(64) DEFAULT NULL COMMENT '修改人',
        `CREATE_TIME` varchar(64) DEFAULT NULL COMMENT '创建时间',
        `CREATE_USER` varchar(64) DEFAULT NULL COMMENT '创建人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;



